import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'installation',
    'quickstart',
    'architecture',
    'non-custodial',
    'nl-planner',
    {
      type: 'category',
      label: 'API',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
